# Generated by Django 4.0.5 on 2022-06-13 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='project_file',
            field=models.FileField(null=True, upload_to='project_data'),
        ),
    ]
