# Generated by Django 4.0.5 on 2022-06-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_post_project_image_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='project_file',
            field=models.FileField(null=True, upload_to='forum/project_data'),
        ),
        migrations.AlterField(
            model_name='post',
            name='project_image',
            field=models.FileField(null=True, upload_to='forum/project_image'),
        ),
    ]
