# Generated by Django 4.0.5 on 2022-06-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_post_project_file_alter_post_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='project_image',
            field=models.ImageField(null=True, upload_to='project_images/'),
        ),
    ]
